# Generated by Django 5.0.6 on 2024-06-14 08:10

import cardekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0002_carlist_chasisnum_carlist_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chasisnum',
            field=models.CharField(blank=True, max_length=50, validators=[cardekho_app.models.alphanumeric]),
        ),
    ]
