# Generated by Django 5.0.1 on 2024-05-31 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaicode', '0002_chaireview_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CERTIFICATE', to='chaicode.chaivariety')),
            ],
        ),
    ]
